# Generated by Django 3.1.7 on 2021-04-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Train number')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_shaxar', to='cities.city', verbose_name='Qaysi shaxardan')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Poyezd xos nomi')),
                ('travel_time', models.PositiveSmallIntegerField(verbose_name='Sayohat vaqti')),
                ('start_train_day', models.DateField(blank=True, null=True)),
                ('start_train_time', models.TimeField(blank=True, null=True)),
                ('end_train_day', models.DateField(blank=True, null=True)),
                ('place', models.IntegerField(default=0)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city_set', to='cities.city', verbose_name='Qaysi shaxardan')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city_set', to='cities.city', verbose_name='Qaysi shaxarga')),
            ],
            options={
                'verbose_name': 'Poyezd',
                'verbose_name_plural': 'Poyezdlar ombori',
            },
        ),
    ]
