# Generated by Django 3.1.5 on 2021-02-03 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_auto_20210202_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='trave_time',
            new_name='travel_time',
        ),
    ]
