# Generated by Django 3.1.7 on 2021-04-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='about_short',
            new_name='shahar_haqida_qisqa',
        ),
    ]
